### ISSUE TITLE
<script>alert(1)</script>

### ISSUE THREAD

**Issue by lone0x0** [FoxLinlab/Lenovo-XiaoXin-Air15-Iwl#1]

**Comment by FoxLinlab** [comment]
有的，该项目下就是呀。

**Comment by FoxLinlab** [comment]
留个联系方式 我发你

**Comment by lone0x0** [comment]
> 留个联系方式 我发你

ipatevblagoiar1992@gmail.com
发到这个邮箱吧

**Comment by lone0x0** [comment]
你好

**Comment by FoxLinlab** [comment]
有点忙，刚看到，查收:)

**Comment by FoxLinlab** [comment]
EFI已发，希望帮到你。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FoxLinlab/Lenovo-XiaoXin-Air15-Iwl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 下午4:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FoxLinlab/Lenovo-XiaoXin-Air15-Iwl] 你好 请问一下 有efi吗 (Issue #1)



 你好
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

EFI.zip (114.47M, 2023年02月20日 09:23 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=043731387f4cebceb158ab261e3301190e51015a0f040654150650590a1e075308531c5a5e51061b0d5601090b5257575e06060c383433737e7e1f425143330b&t=exs_ftn_download&code=87188336

**Comment by lone0x0** [comment]
你好 师傅 我用了你这个efi 在12.5版本 安装成功了 但是亮度无法调节 触摸板移动得很慢
你确定你的是小新air15 iwl 8代u吗
